CREATE USER PARKING_LOT_ADMIN LOGIN;

GRANT SELECT, UPDATE ON TABLE ADMIN TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PARKING_LOT TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SECTIONS TO PARKING_LOT_ADMIN;

GRANT SELECT,  UPDATE ON TABLE SPACE_TYPE TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PARKING_SPACE TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PARKING_SENSOR TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GATES TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USERS TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_PARKING_HISTORY TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_WALLET TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_WALLET_HISTORY TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE BILL TO PARKING_LOT_ADMIN;

-- Grant execute permissions on all procedures in a schema to a role
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO PARKING_LOT_ADMIN;

-- Grant execute permissions on all procedures in a schema to a role
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO PARKING_LOT_ADMIN;


-- Add more tables as needed
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO PARKING_LOT_ADMIN;
