psql -U SmartParkingManagement

CREATE ROLE USER;

 GRANT ALL ON SCHEMA PUBLIC TO USER;

 GRANT SELECT,UPDATE,INSERT ON TABLE USERS IN SCHEMA PUBLIC TO USER ;
 GRANT SELECT ON TABLE BILL IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE PARKING_LOT IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE PARKING_SPACE IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE SECTIONS IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE SPACE_TYPE IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_PARKING_HISTORY IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_WALLET IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_WALLET_HISTORY IN SCHEMA PUBLIC TO USER;
