psql -U SmartParkingManagement

CREATE ROLE USER;

CREATE ROLE USER1 WITH PASSWORD 'USER1@SPM' LOGIN;
CREATE ROLE USER2 WITH PASSWORD 'USER2@SPM' LOGIN;
CREATE ROLE USER3 WITH PASSWORD 'USER3@SPM' LOGIN;
CREATE ROLE USER4 WITH PASSWORD 'USER4@SPM' LOGIN;

ALTER ROLE USER1,USER2,USER3,USER4 IN GROUP USER;

 GRANT ALL ON SCHEMA PUBLIC TO USER;

 GRANT SELECT,UPDATE,INSERT ON TABLE USERS IN SCHEMA PUBLIC TO USER ;
 GRANT SELECT ON TABLE BILL IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE PARKING_LOT IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE PARKING_SPACE IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE SECTIONS IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE SPACE_TYPE IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_PARKING_HISTORY IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_WALLET IN SCHEMA PUBLIC TO USER;
 GRANT SELECT ON TABLE USER_WALLET_HISTORY IN SCHEMA PUBLIC TO USER;
