CREATE VIEW SENSORS_UNDER_MAINTENANCE AS 
SELECT 
PS.SENSOR_ID, PS.TAG, PAS.NAME, 'MAINTENANCE' AS STATUS
FROM PARKING_SENSOR PS
JOIN PARKING_SPACE PAS ON PAS.SPACE_ID = PS.SPACE_ID
WHERE STATUS = 'INACTIVE';


CREATE VIEW WORING_SENSORS AS 
SELECT 
PS.SENSOR_ID, PS.TAG, PAS.NAME, 'WORKING' AS STATUS
FROM PARKING_SENSOR PS
JOIN PARKING_SPACE PAS ON PAS.SPACE_ID = PS.SPACE_ID
WHERE STATUS = 'ACTIVE';

