---------- TRIGGERS ----------
CREATE EXTENSION pgcrypto;
BEGIN;

--1 TRIGGER FOR CREATING WALLET FOR USER --
CREATE OR REPLACE FUNCTION parking_schema.CREATE_WALLET_ON_REG_USER()
RETURNS TRIGGER
AS $$
BEGIN
    INSERT INTO parking_schema.USER_WALLET(USER_ID, BALANCE) VALUES (NEW.USER_ID, 0);
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS CREATE_WALLET_ON_REG_USER_TRIGGER ON parking_schema.USERS;
CREATE TRIGGER CREATE_WALLET_ON_REG_USER_TRIGGER
AFTER INSERT
ON parking_schema.USERS
FOR EACH ROW EXECUTE FUNCTION parking_schema.CREATE_WALLET_ON_REG_USER();