CREATE USER PARKING_LOT_ADMIN LOGIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE parking_schema.BILL TO PARKING_LOT_ADMIN;

GRANT SELECT, UPDATE ON TABLE parking_schema.SPACE_TYPE TO PARKING_LOT_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE parking_schema.USER_WALLET_HISTORY TO PARKING_LOT_ADMIN;

