---------- TRIGGERS ----------
BEGIN;
-- TRIGGER FOR CREATING WALLET FOR USER --
CREATE OR REPLACE FUNCTION smart_parking.CREATE_WALLET_ON_REG_USER()
RETURNS TRIGGER
AS $$
BEGIN
    INSERT INTO smart_parking.USER_WALLET(USER_ID, BALANCE) VALUES (NEW.USER_ID, 0);
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

DROP TRIGGER IF EXISTS CREATE_WALLET_ON_REG_USER_TRIGGER ON smart_parking.USERS;
CREATE TRIGGER CREATE_WALLET_ON_REG_USER_TRIGGER
AFTER INSERT
ON smart_parking.USERS
FOR EACH ROW EXECUTE FUNCTION smart_parking.CREATE_WALLET_ON_REG_USER();

SAVEPOINT SAVEPOINT_02;
-- ROLLBACK, IF REQUIRED
COMMIT;