-SENSORS UNDER MAINTENANCE
CREATE VIEW SENSORS_UNDER_MAINTENANCE AS 
SELECT 
PS.SENSOR_ID, PS.TAG, PAS.NAME, 'MAINTENANCE' AS STATUS
FROM PARKING_SENSOR PS
JOIN PARKING_SPACE PAS ON PAS.SPACE_ID = PS.SPACE_ID
WHERE STATUS = 'INACTIVE';

-- WORKING SENSORS
CREATE VIEW WORING_SENSORS AS 
SELECT 
PS.SENSOR_ID, PS.TAG, PAS.NAME, 'WORKING' AS STATUS
FROM PARKING_SENSOR PS
JOIN PARKING_SPACE PAS ON PAS.SPACE_ID = PS.SPACE_ID
WHERE STATUS = 'ACTIVE';

-- DAILY PARKING TRENDS
CREATE VIEW DAILY_PARKING_TRENDS AS 
SELECT COUNT(*) AS TOTAL, DATE_TRUNC('day', GSR.DATE) AS DAY
FROM GATE_SENSOR_READING GSR
JOIN GATES GA ON GA.SENSOR_TAG = GSR.SENSOR_TAG
WHERE GA.NAME = 'ENTRY'
GROUP BY DAY, TOTAL;