
--1 ENTRY GATE DETECT USER
-- Insert data into GATE_SENSOR_READING table
INSERT INTO GATE_SENSOR_READING (DATE, SENSOR_TAG, RFID_TAG) VALUES
 (CURRENT_TIMESTAMP, 'ENT001', 'ABC123');
  
SELECT * FROM GATE_SENSOR_READING;
SELECT * FROM USER_PARKING_HISTORY;

--2 USER CHECK IN 
INSERT INTO PARKING_SENSOR_READING(READING, DATE, SENSOR_ID) VALUES
(0, CURRENT_TIMESTAMP, 1);

SELECT * FROM PARKING_SENSOR_READING;
SELECT * FROM USER_PARKING_HISTORY;

--3 USER CHECK OUT AND BILL IS GENERATED
INSERT INTO PARKING_SENSOR_READING(READING, DATE, SENSOR_ID) VALUES
(1, CURRENT_TIMESTAMP, 1);

SELECT * FROM PARKING_SENSOR_READING;
SELECT * FROM USER_PARKING_HISTORY;
SELECT * FROM BILL;
SELECT * FROM USER_WALLET;