-- QUERY FOR REGISTER USER
SELECT 
    EMAIL, 
    PHONE, 
    FIRST_NAME, 
    LAST_NAME, 
    GENDER, 
    AGE, 
    STATUS,
    RFID_TAG,
    PASSWORD
FROM parking_schema.USERS
ORDER BY USER_ID;


-- QUERY FOR ALL PARKING SPACE
SELECT 
    PARKING_SPACE.NAME AS PARKING_SPACE, 
    STATUS, 
    PARKING_SPACE.TYPE AS PARKING_SPACE_TYPE
FROM parking_schema.PARKING_SPACE;

-- QUERY FOR ALL AVAILABLE PARKING SPACE OF TWO WHEELERS 
SELECT 
        PARKING_SPACE.NAME,
        PARKING_SPACE.TYPE
    FROM PARKING_SPACE
    WHERE PARKING_SPACE.TYPE = 'TWO-WHEELER'
        AND PARKING_SPACE.STATUS = 'AVAILABLE';


-- QUERY FOR ALL AVAILABLE PARKING SPACE OF FOUR WHEELERS 
SELECT 
        PARKING_SPACE.NAME,
        PARKING_SPACE.TYPE
    FROM PARKING_SPACE
    WHERE PARKING_SPACE.TYPE = 'FOUR-WHEELER'
        AND PARKING_SPACE.STATUS = 'AVAILABLE';


-- QUERY TO UPDATE THE STATUS OF PARKING SPACE TO MAINTENANCE
UPDATE PARKING_SPACE
SET PARKING_SPACE.STATUS = 'MAINTENANCE'
WHERE PARKING_SPACE.NAME = 'SEC1-SP1'

-- QUERY FOR USER_WALLET OF PARTICULAR USER
 SELECT
        CASE
            WHEN uw.TYPE = 'C' THEN 'Credit'
            WHEN uw.TYPE = 'D' THEN 'Debit'
            ELSE uw.TYPE  -- Handle any other types if needed
        END AS TRANSACTION_TYPE,
        uw.AMOUNT,
        uw.DATE AS TRANSACTION_DATE
    FROM
        USER_WALLET_HISTORY uw
    JOIN
        USER_WALLET w ON uw.WALLET_ID = w.WALLET_ID
    WHERE
        w.USER_ID = p_user_id;

-- DELETE USER ACCOUNT
DELETE FROM USERS CASCADE WHERE USER_ID = 1; 
-- Replace 1 with the ID of the user you want to delete

-- UPDATE USER STATUS
UPDATE USERS SET STATUS = 'INACTIVE' WHERE USER_ID = 1; 
-- Replace 1 with the ID of the user you want to update