


CREATE USER PARKING_LOT_ADMIN LOGIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USERS TO PARKING_LOT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_WALLET TO PARKING_LOT_ADMIN;

CREATE USER DEV_USER LOGIN;

GRANT SELECT ON TABLE USERS TO DEV_USER;
GRANT SELECT ON TABLE USER_WALLET TO DEV_USER;

-- GRANT SELECT ON VIEWS 
GRANT SELECT ON parking_schema.AVAILABLE_PARKING_SPACES TO  DEV_USER;
GRANT SELECT ON parking_schema.USER_WALLET_BALANCE TO  DEV_USER;
GRANT SELECT ON parking_schema.USER_WALLET_TRANSACTIONS TO  DEV_USER;
GRANT SELECT ON parking_schema.USER_RUNNING_COST TO  DEV_USER;