


CREATE USER PARKING_LOT_ADMIN LOGIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USERS TO PARKING_LOT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_WALLET TO PARKING_LOT_ADMIN;

CREATE USER CUSTOMER LOGIN;

GRANT SELECT, INSERT, UPDATE  ON TABLE USERS TO CUSTOMER;
GRANT UPDATE ON TABLE USER_WALLET TO CUSTOMER;

-- GRANT SELECT ON VIEWS 
GRANT SELECT ON parking_schema.AVAILABLE_PARKING_SPACES TO  CUSTOMER;
GRANT SELECT ON parking_schema.USER_WALLET_BALANCE TO  CUSTOMER;
GRANT SELECT ON parking_schema.USER_WALLET_TRANSACTIONS TO  CUSTOMER;
GRANT SELECT ON parking_schema.USER_RUNNING_COST TO  CUSTOMER;